#!/bin/bash

docker ps -a | grep osp-old-builder &>/dev/null && docker rm osp-old-builder &> /dev/null
docker images | grep osp-old-builder &>/dev/null && docker rmi osp-old-builder &> /dev/null

OS=$(uname)
docker &> /dev/null
NEED_DOCKER=$?

if [ $NEED_DOCKER -ne 0 ]
then
  if [ $OS = "Darwin" ]
  then
    open https://store.docker.com/editions/community/docker-ce-desktop-mac
    read -p "Install Docker for Mac and then press any key once installed and running." -n1 -s && echo
  else
    echo "Install Docker and then press any key once installed and running."
    read -p "See the README file for link to help on this" -n1 -s && echo
  fi
fi

docker build -t osp-old-builder .
docker create -it -v $PWD/opt:/opt --privileged  --name osp-old-builder -h osp-old-builder osp-old-builder

exit 0
